# Generated by Django 4.0.2 on 2022-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0005_alter_productrecord_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecord',
            name='ingredients',
            field=models.JSONField(default={}),
        ),
    ]
