# Generated by Django 4.0.2 on 2022-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0006_alter_productrecord_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecord',
            name='ingredients',
            field=models.JSONField(default=dict),
        ),
    ]
