# Generated by Django 4.0.2 on 2022-03-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0007_alter_productrecord_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
