# Generated by Django 4.0.2 on 2022-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0008_alter_productrecord_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
