# Generated by Django 4.0.2 on 2022-03-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0009_alter_productrecord_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrecord',
            old_name='productName',
            new_name='product_name',
        ),
    ]
