# Generated by Django 4.0.2 on 2022-03-25 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0010_rename_productname_productrecord_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True)),
                ('sales_report', models.JSONField(default=dict)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profitmaximizer.businessowner')),
            ],
        ),
    ]
