# Generated by Django 4.0.2 on 2022-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0011_salesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
