# Generated by Django 4.0.2 on 2022-03-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0013_productionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecord',
            name='ingredient_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
