# Generated by Django 4.0.2 on 2022-05-10 03:29

from django.db import migrations, models
import profitmaximizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0016_ingredientrecord_unique_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='photo',
            field=models.ImageField(blank=True, upload_to=profitmaximizer.models.business_owner_photos_dir),
        ),
    ]
