# Generated by Django 4.0.2 on 2022-05-10 05:08

from django.db import migrations, models
import profitmaximizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0018_alter_businessowner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='photo',
            field=models.ImageField(blank=True, upload_to=profitmaximizer.models.business_owner_photos_dir),
        ),
    ]
