# Generated by Django 4.0.2 on 2022-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitmaximizer', '0019_alter_businessowner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='is_optimal',
            field=models.BooleanField(default=False),
        ),
    ]
